name: Publish
on:
  workflow_run:
    workflows: ['CI']
    branches:
      - main
    types:
      - completed

jobs:
  publish:
    name: Publish a new release
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write       # To publish a GitHub release & commit version updates
      issues: write         # To comment on released issues
      pull-requests: write  # To comment on released pull requests
      id-token: write       # If needed for OIDC authentication (e.g., with external registries)
      packages: write       # To publish to GitHub Packages
    env:
      NODE_VERSION: lts/*
      PNPM_VERSION: 10
      REGISTRY_URL: "https://npm.pkg.github.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}

      - name: Publish a new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release